<a href="https://colab.research.google.com/github/girijadesai390-web/Data-Cleaning-Practice/blob/main/Data_cleaning_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
data = {
    "Name":[" John","Alice","johnny","Bob","priya","Alice",None],
    "Age":[24,23,25,None,25,23,35],
    "City":["Pune","sangli","Kolhapur ","Mumbai"," kolhapur","sangli",None],
    "Gender":["Male","female","M","male","f","female","M"]
}

df = pd.DataFrame(data)
df

     Name   Age       City  Gender
0    John  24.0       Pune    Male
1   Alice  23.0     sangli  female
2  johnny  25.0  Kolhapur        M
3     Bob   NaN     Mumbai    male
4   priya  25.0   kolhapur       f
5   Alice  23.0     sangli  female
6    None  35.0       None       M

In [ ]:
df.isnull().sum()

Name      1
Age       1
City      1
Gender    0
dtype: int64

In [ ]:
df.describe()

             Age
count   6.000000
mean   25.833333
std     4.578937
min    23.000000
25%    23.250000
50%    24.500000
75%    25.000000
max    35.000000

In [ ]:
df["Age"].fillna(df["Age"].mean(),inplace=True)
df

/tmp/ipykernel_684/2079956988.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].mean(),inplace=True)

     Name        Age       City  Gender
0    John  24.000000       Pune    Male
1   Alice  23.000000     sangli  female
2  johnny  25.000000  Kolhapur        M
3     Bob  25.833333     Mumbai    male
4   priya  25.000000   kolhapur       f
5   Alice  23.000000     sangli  female
6    None  35.000000       None       M

In [ ]:
df.isnull().sum()

Name      1
Age       0
City      1
Gender    0
dtype: int64

In [ ]:
df["Name"].fillna("unknown",inplace=True)
df

/tmp/ipykernel_684/2961181316.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Name"].fillna("unknown",inplace=True)

      Name        Age       City  Gender
0     John  24.000000       Pune    Male
1    Alice  23.000000     sangli  female
2   johnny  25.000000  Kolhapur        M
3      Bob  25.833333     Mumbai    male
4    priya  25.000000   kolhapur       f
5    Alice  23.000000     sangli  female
6  unknown  35.000000       None       M

In [ ]:
df["City"].fillna("unknown",inplace=True)
df

/tmp/ipykernel_684/3614845296.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["City"].fillna("unknown",inplace=True)

      Name        Age       City  Gender
0     John  24.000000       Pune    Male
1    Alice  23.000000     sangli  female
2   johnny  25.000000  Kolhapur        M
3      Bob  25.833333     Mumbai    male
4    priya  25.000000   kolhapur       f
5    Alice  23.000000     sangli  female
6  unknown  35.000000    unknown       M

In [ ]:
df.isnull().sum()

Name      0
Age       0
City      0
Gender    0
dtype: int64

In [ ]:
df["Name"]=df["Name"].str.title()
df

      Name        Age       City  Gender
0     John  24.000000       Pune    Male
1    Alice  23.000000     sangli  female
2   Johnny  25.000000  Kolhapur        M
3      Bob  25.833333     Mumbai    male
4    Priya  25.000000   kolhapur       f
5    Alice  23.000000     sangli  female
6  Unknown  35.000000    unknown       M

In [ ]:
df["City"]=df["City"].str.capitalize()
df

      Name        Age       City  Gender
0     John  24.000000       Pune    Male
1    Alice  23.000000     Sangli  female
2   Johnny  25.000000  Kolhapur        M
3      Bob  25.833333     Mumbai    male
4    Priya  25.000000   kolhapur       f
5    Alice  23.000000     Sangli  female
6  Unknown  35.000000    Unknown       M

In [ ]:
df["City"]=df["City"].str.strip()
df["City"]=df["City"].str.capitalize()
df

      Name        Age      City  Gender
0     John  24.000000      Pune    Male
1    Alice  23.000000    Sangli  female
2   Johnny  25.000000  Kolhapur       M
3      Bob  25.833333    Mumbai    male
4    Priya  25.000000  Kolhapur       f
5    Alice  23.000000    Sangli  female
6  Unknown  35.000000   Unknown       M

In [ ]:
df["Name"]=df["Name"].str.strip()
df

      Name        Age      City  Gender
0     John  24.000000      Pune    Male
1    Alice  23.000000    Sangli  female
2   Johnny  25.000000  Kolhapur       M
3      Bob  25.833333    Mumbai    male
4    Priya  25.000000  Kolhapur       f
5    Alice  23.000000    Sangli  female
6  Unknown  35.000000   Unknown       M

In [ ]:
def clean_gender(gender):
  if gender=="M" or gender=="Male" or gender=="male":
    return "Male"
  elif gender=="f" or gender=="female" or gender=="Female":
    return "Female"
  else:
    return "Unknown"

In [ ]:
df["Gender"] =df["Gender"].apply(clean_gender)
df

      Name        Age      City  Gender
0     John  24.000000      Pune    Male
1    Alice  23.000000    Sangli  Female
2   Johnny  25.000000  Kolhapur    Male
3      Bob  25.833333    Mumbai    Male
4    Priya  25.000000  Kolhapur  Female
5    Alice  23.000000    Sangli  Female
6  Unknown  35.000000   Unknown    Male

In [ ]:
df=df.drop_duplicates()
df

      Name        Age      City  Gender
0     John  24.000000      Pune    Male
1    Alice  23.000000    Sangli  Female
2   Johnny  25.000000  Kolhapur    Male
3      Bob  25.833333    Mumbai    Male
4    Priya  25.000000  Kolhapur  Female
6  Unknown  35.000000   Unknown    Male

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, 0 to 6
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    6 non-null      object
 1   Age     6 non-null      float64
 2   City    6 non-null      object
 3   Gender  6 non-null      object
dtypes: float64(1), object(3)
memory usage: 240.0+ bytes

In [ ]:
np.dtype(df["Age"])

dtype('float64')

In [ ]:
df["Age"] = df["Age"].astype(int)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, 0 to 6
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    6 non-null      object
 1   Age     6 non-null      int64
 2   City    6 non-null      object
 3   Gender  6 non-null      object
dtypes: int64(1), object(3)
memory usage: 240.0+ bytes

/tmp/ipykernel_684/2887538823.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Age"] = df["Age"].astype(int)

In [ ]:
df

      Name  Age      City  Gender
0     John   24      Pune    Male
1    Alice   23    Sangli  Female
2   Johnny   25  Kolhapur    Male
3      Bob   25    Mumbai    Male
4    Priya   25  Kolhapur  Female
6  Unknown   35   Unknown    Male